// Code generated by eevee. DO NOT EDIT!

package request

import (
	"golang.org/x/xerrors"
	"net/http"
)

type UserGetter struct {
	UserID  uint64
	Session string
}

type UserGetterBuilder struct {
	userID *uint64
}

func (b *UserGetterBuilder) SetUserID(a uint64) *UserGetterBuilder {
	b.userID = &a
	return b
}

func (b *UserGetterBuilder) Build(r *http.Request) (*UserGetter, error) {
	req := &UserGetter{}
	if b.userID == nil {
		return nil, xerrors.New("userID is required. but doesn't assigned to builder")
	}
	if b.userID != nil {
		req.UserID = *b.userID
	}
	req.Session = r.Header.Get("X-Session")
	return req, nil
}
