// Code generated by eevee. DO NOT EDIT!

package factory

import (
	"api/entity"
	"api/model"
)

func DefaultField() *model.Field {
	value := &model.Field{Field: &entity.Field{
		Difficulty: 0,
		ID:         0,
		Level:      0,
		LocationX:  0,
		LocationY:  0,
		Name:       "",
		ObjectNum:  0,
	}}
	return value
}

func DefaultFields() *model.Fields {
	values := &model.Fields{}
	{
		value := &model.Field{Field: &entity.Field{
			Difficulty: 0,
			ID:         0,
			Level:      0,
			LocationX:  0,
			LocationY:  0,
			Name:       "",
			ObjectNum:  0,
		}}
		values.Add(value)
	}
	return values
}
