// Code generated by eevee. DO NOT EDIT!

package factory

import (
	"api/entity"
	"api/model"
	"context"
)

func DefaultUserField() *model.UserField {
	field := DefaultField()
	value := &model.UserField{UserField: &entity.UserField{
		FieldID: 0,
		ID:      0,
		UserID:  0,
	}}
	value.Field = func(context.Context) (*model.Field, error) {
		return field, nil
	}
	return value
}

func DefaultUserFields() *model.UserFields {
	values := &model.UserFields{}
	{
		field := DefaultField()
		value := &model.UserField{UserField: &entity.UserField{
			FieldID: 0,
			ID:      0,
			UserID:  0,
		}}
		value.Field = func(context.Context) (*model.Field, error) {
			return field, nil
		}
		values.Add(value)
	}
	return values
}
