// Code generated by eevee. DO NOT EDIT!

package model

import (
	"api/entity"
	"api/model"
)

func DefaultSkill() *model.Skill {
	value := model.NewSkill(&entity.Skill{
		ID:          uint64(0x0),
		SkillEffect: "",
	}, nil)
	return value
}

func DefaultsSkill() *model.Skills {
	values := model.NewSkills(entity.Skills{})
	values.Add(DefaultSkill())
	return values
}
