// Code generated by eevee. DO NOT EDIT!

package model

import (
	"api/entity"
	"api/model"
	"context"
)

func DefaultUser() *model.User {
	value := model.NewUser(&entity.User{
		Age:       uint64(0x0),
		FieldID:   uint64(0x0),
		GroupID:   uint64(0x0),
		ID:        uint64(0x0),
		Name:      "",
		Sex:       "",
		SkillID:   uint64(0x0),
		SkillRank: uint64(0x0),
		WorldID:   uint64(0x0),
	}, nil)
	value.UserFields = func(context.Context) (*model.UserFields, error) {
		return DefaultUserField(), nil
	}
	value.Skill = func(context.Context) (*model.Skill, error) {
		return DefaultSkill(), nil
	}
	value.World = func(context.Context) (*model.World, error) {
		return DefaultWorld(), nil
	}
	return value
}

func DefaultsUser() *model.Users {
	values := model.NewUsers(entity.Users{})
	values.Add(DefaultUser())
	return values
}
