// Code generated by eevee. DO NOT EDIT!

package model

import (
	"api/entity"
	"api/model"
)

func DefaultWorld() *model.World {
	value := model.NewWorld(&entity.World{
		ID:   uint64(0x0),
		Name: "",
	}, nil)
	return value
}

func DefaultsWorld() *model.Worlds {
	values := model.NewWorlds(entity.Worlds{})
	values.Add(DefaultWorld())
	return values
}
