package dao

import (
	"context"
	"database/sql"
	"eevee/entity"
	"fmt"
	"strings"

	"golang.org/x/xerrors"
)

type Field interface {
	Count(context.Context) (int64, error)
	Create(context.Context, *entity.Field) error
	Delete(context.Context, *entity.Field) error
	DeleteByDifficultyAndLevel(context.Context, int, int) error
	DeleteByID(context.Context, uint64) error
	DeleteByIDs(context.Context, []uint64) error
	DeleteByLocationXAndLocationY(context.Context, int, int) error
	DeleteByName(context.Context, string) error
	DeleteByNames(context.Context, []string) error
	DeleteByObjectNum(context.Context, int) error
	DeleteByObjectNums(context.Context, []int) error
	FindAll(context.Context) (entity.Fields, error)
	FindByDifficulties(context.Context, []int) (entity.Fields, error)
	FindByDifficulty(context.Context, int) (entity.Fields, error)
	FindByDifficultyAndLevel(context.Context, int, int) (entity.Fields, error)
	FindByID(context.Context, uint64) (*entity.Field, error)
	FindByIDs(context.Context, []uint64) (entity.Fields, error)
	FindByLocationX(context.Context, int) (entity.Fields, error)
	FindByLocationXAndLocationY(context.Context, int, int) (*entity.Field, error)
	FindByLocationXes(context.Context, []int) (entity.Fields, error)
	FindByName(context.Context, string) (*entity.Field, error)
	FindByNames(context.Context, []string) (entity.Fields, error)
	FindByObjectNum(context.Context, int) (entity.Fields, error)
	FindByObjectNums(context.Context, []int) (entity.Fields, error)
	Update(context.Context, *entity.Field) error
	UpdateByDifficultyAndLevel(context.Context, int, int, map[string]interface{}) error
	UpdateByID(context.Context, uint64, map[string]interface{}) error
	UpdateByIDs(context.Context, []uint64, map[string]interface{}) error
	UpdateByLocationXAndLocationY(context.Context, int, int, map[string]interface{}) error
	UpdateByName(context.Context, string, map[string]interface{}) error
	UpdateByNames(context.Context, []string, map[string]interface{}) error
	UpdateByObjectNum(context.Context, int, map[string]interface{}) error
	UpdateByObjectNums(context.Context, []int, map[string]interface{}) error
	ExtendMethod() error
}

type FieldImpl struct {
	tx *sql.Tx
}

func NewField(ctx context.Context, tx *sql.Tx) Field {
	return &FieldImpl{tx: tx}
}

// generated by eevee
func (d *FieldImpl) Count(ctx context.Context) (r int64, e error) {
	var value int64
	query := "COUNT(*) FROM `fields`"
	if err := d.tx.QueryRowContext(ctx, query).Scan(&value); err != nil {
		if err == sql.ErrNoRows {
			return 0, nil
		}
		return 0, xerrors.Errorf("failure query %s: %w", query, err)
	}
	return value, nil
}

// generated by eevee
func (d *FieldImpl) Create(ctx context.Context, value *entity.Field) (e error) {
	query := "INSERT INTO `fields` (`id`, `name`, `location_x`, `location_y`, `object_num`, `level`, `difficulty`) VALUES (?, ?, ?, ?, ?, ?, ?)"
	result, err := d.tx.ExecContext(ctx, query, value.ID, value.Name, value.LocationX, value.LocationY, value.ObjectNum, value.Level, value.Difficulty)
	if err != nil {
		return xerrors.Errorf("failure query %s: %w", query, err)
	}
	id, err := result.LastInsertId()
	if err != nil {
		return xerrors.Errorf("cannot get LastInsertId: %w", err)
	}
	value.ID = uint64(id)
	return nil
}

// generated by eevee
func (d *FieldImpl) Delete(ctx context.Context, value *entity.Field) (e error) {
	query := "DELETE FROM `fields` WHERE id = ?"
	if _, err := d.tx.ExecContext(ctx, query, value.ID); err != nil {
		return xerrors.Errorf("failure query %s: %w", query, err)
	}
	return nil
}

// generated by eevee
func (d *FieldImpl) DeleteByDifficultyAndLevel(ctx context.Context, a0 int, a1 int) (e error) {
	query := "DELETE FROM `fields` WHERE `difficulty` = ? AND `level` = ?"
	if _, err := d.tx.ExecContext(ctx, query, a0, a1); err != nil {
		return xerrors.Errorf("failure query %s: %w", query, err)
	}
	return nil
}

// generated by eevee
func (d *FieldImpl) DeleteByID(ctx context.Context, a0 uint64) (e error) {
	query := "DELETE FROM `fields` WHERE `id` = ?"
	if _, err := d.tx.ExecContext(ctx, query, a0); err != nil {
		return xerrors.Errorf("failure query %s: %w", query, err)
	}
	return nil
}

// generated by eevee
func (d *FieldImpl) DeleteByIDs(ctx context.Context, a0 []uint64) (e error) {
	args := []interface{}{}
	placeholders := make([]string, 0, len(a0))
	for _, v := range a0 {
		args = append(args, v)
		placeholders = append(placeholders, "?")
	}
	query := fmt.Sprintf("DELETE FROM `fields` WHERE `id` IN (%s)", strings.Join(placeholders, ", "))
	if _, err := d.tx.ExecContext(ctx, query, args...); err != nil {
		return xerrors.Errorf("failure query %s: %w", query, err)
	}
	return nil
}

// generated by eevee
func (d *FieldImpl) DeleteByLocationXAndLocationY(ctx context.Context, a0 int, a1 int) (e error) {
	query := "DELETE FROM `fields` WHERE `location_x` = ? AND `location_y` = ?"
	if _, err := d.tx.ExecContext(ctx, query, a0, a1); err != nil {
		return xerrors.Errorf("failure query %s: %w", query, err)
	}
	return nil
}

// generated by eevee
func (d *FieldImpl) DeleteByName(ctx context.Context, a0 string) (e error) {
	query := "DELETE FROM `fields` WHERE `name` = ?"
	if _, err := d.tx.ExecContext(ctx, query, a0); err != nil {
		return xerrors.Errorf("failure query %s: %w", query, err)
	}
	return nil
}

// generated by eevee
func (d *FieldImpl) DeleteByNames(ctx context.Context, a0 []string) (e error) {
	args := []interface{}{}
	placeholders := make([]string, 0, len(a0))
	for _, v := range a0 {
		args = append(args, v)
		placeholders = append(placeholders, "?")
	}
	query := fmt.Sprintf("DELETE FROM `fields` WHERE `name` IN (%s)", strings.Join(placeholders, ", "))
	if _, err := d.tx.ExecContext(ctx, query, args...); err != nil {
		return xerrors.Errorf("failure query %s: %w", query, err)
	}
	return nil
}

// generated by eevee
func (d *FieldImpl) DeleteByObjectNum(ctx context.Context, a0 int) (e error) {
	query := "DELETE FROM `fields` WHERE `object_num` = ?"
	if _, err := d.tx.ExecContext(ctx, query, a0); err != nil {
		return xerrors.Errorf("failure query %s: %w", query, err)
	}
	return nil
}

// generated by eevee
func (d *FieldImpl) DeleteByObjectNums(ctx context.Context, a0 []int) (e error) {
	args := []interface{}{}
	placeholders := make([]string, 0, len(a0))
	for _, v := range a0 {
		args = append(args, v)
		placeholders = append(placeholders, "?")
	}
	query := fmt.Sprintf("DELETE FROM `fields` WHERE `object_num` IN (%s)", strings.Join(placeholders, ", "))
	if _, err := d.tx.ExecContext(ctx, query, args...); err != nil {
		return xerrors.Errorf("failure query %s: %w", query, err)
	}
	return nil
}

// generated by eevee
func (d *FieldImpl) FindAll(ctx context.Context) (r entity.Fields, e error) {
	values := entity.Fields{}
	query := "SELECT `id`, `name`, `location_x`, `location_y`, `object_num`, `level`, `difficulty` FROM `fields`"
	rows, err := d.tx.QueryContext(ctx, query)
	if err != nil {
		return values, xerrors.Errorf("falure query %s: %w", query, err)
	}
	defer func() {
		if err := rows.Close(); err != nil {
			e = xerrors.Errorf("cannot close rows: %w", err)
		}
	}()
	for rows.Next() {
		var value entity.Field
		if err := rows.Scan(&value.ID, &value.Name, &value.LocationX, &value.LocationY, &value.ObjectNum, &value.Level, &value.Difficulty); err != nil {
			return values, xerrors.Errorf("cannot scan value: %w", err)
		}
		values = append(values, &value)
	}
	return values, nil
}

// generated by eevee
func (d *FieldImpl) FindByDifficulties(ctx context.Context, a0 []int) (r entity.Fields, e error) {
	values := entity.Fields{}
	query := "SELECT `id`, `name`, `location_x`, `location_y`, `object_num`, `level`, `difficulty` FROM `fields` WHERE `difficulty` IN (%s)"
	args := []interface{}{}
	placeholders := make([]string, 0, len(a0))
	for _, v := range a0 {
		args = append(args, v)
		placeholders = append(placeholders, "?")
	}
	selectQuery := fmt.Sprintf(query, strings.Join(placeholders, ", "))
	rows, err := d.tx.QueryContext(ctx, selectQuery, args...)
	if err != nil {
		return values, xerrors.Errorf("failure query %s: %w", query, err)
	}
	defer func() {
		if err := rows.Close(); err != nil {
			e = xerrors.Errorf("cannot close rows: %w", err)
		}
	}()
	for rows.Next() {
		var value entity.Field
		if err := rows.Scan(
			&value.ID,
			&value.Name,
			&value.LocationX,
			&value.LocationY,
			&value.ObjectNum,
			&value.Level,
			&value.Difficulty,
		); err != nil {
			return values, xerrors.Errorf("cannot scan value: %w", err)
		}
		values = append(values, &value)
	}
	return values, nil
}

// generated by eevee
func (d *FieldImpl) FindByDifficulty(ctx context.Context, a0 int) (r entity.Fields, e error) {
	values := entity.Fields{}
	query := "SELECT `id`, `name`, `location_x`, `location_y`, `object_num`, `level`, `difficulty` FROM `fields` WHERE `difficulty` = ?"
	rows, err := d.tx.QueryContext(ctx, query, a0)
	if err != nil {
		return values, xerrors.Errorf("failure query %s: %w", query, err)
	}
	defer func() {
		if err := rows.Close(); err != nil {
			e = xerrors.Errorf("cannot close rows: %w", err)
		}
	}()
	for rows.Next() {
		var value entity.Field
		if err := rows.Scan(
			&value.ID,
			&value.Name,
			&value.LocationX,
			&value.LocationY,
			&value.ObjectNum,
			&value.Level,
			&value.Difficulty,
		); err != nil {
			return values, xerrors.Errorf("cannot scan value: %w", err)
		}
		values = append(values, &value)
	}
	return values, nil
}

// generated by eevee
func (d *FieldImpl) FindByDifficultyAndLevel(ctx context.Context, a0 int, a1 int) (r entity.Fields, e error) {
	values := entity.Fields{}
	query := "SELECT `id`, `name`, `location_x`, `location_y`, `object_num`, `level`, `difficulty` FROM `fields` WHERE `difficulty` = ? AND `level` = ?"
	rows, err := d.tx.QueryContext(ctx, query, a0, a1)
	if err != nil {
		return values, xerrors.Errorf("failure query %s: %w", query, err)
	}
	defer func() {
		if err := rows.Close(); err != nil {
			e = xerrors.Errorf("cannot close rows: %w", err)
		}
	}()
	for rows.Next() {
		var value entity.Field
		if err := rows.Scan(
			&value.ID,
			&value.Name,
			&value.LocationX,
			&value.LocationY,
			&value.ObjectNum,
			&value.Level,
			&value.Difficulty,
		); err != nil {
			return values, xerrors.Errorf("cannot scan value: %w", err)
		}
		values = append(values, &value)
	}
	return values, nil
}

// generated by eevee
func (d *FieldImpl) FindByID(ctx context.Context, a0 uint64) (r *entity.Field, e error) {
	var value entity.Field
	query := "SELECT `id`, `name`, `location_x`, `location_y`, `object_num`, `level`, `difficulty` FROM `fields` WHERE `id` = ?"
	if err := d.tx.QueryRowContext(ctx, query, a0).Scan(
		&value.ID,
		&value.Name,
		&value.LocationX,
		&value.LocationY,
		&value.ObjectNum,
		&value.Level,
		&value.Difficulty,
	); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, xerrors.Errorf("failure query %s: %w", query, err)
	}
	return &value, nil
}

// generated by eevee
func (d *FieldImpl) FindByIDs(ctx context.Context, a0 []uint64) (r entity.Fields, e error) {
	values := entity.Fields{}
	query := "SELECT `id`, `name`, `location_x`, `location_y`, `object_num`, `level`, `difficulty` FROM `fields` WHERE `id` IN (%s)"
	args := []interface{}{}
	placeholders := make([]string, 0, len(a0))
	for _, v := range a0 {
		args = append(args, v)
		placeholders = append(placeholders, "?")
	}
	selectQuery := fmt.Sprintf(query, strings.Join(placeholders, ", "))
	rows, err := d.tx.QueryContext(ctx, selectQuery, args...)
	if err != nil {
		return values, xerrors.Errorf("failure query %s: %w", query, err)
	}
	defer func() {
		if err := rows.Close(); err != nil {
			e = xerrors.Errorf("cannot close rows: %w", err)
		}
	}()
	for rows.Next() {
		var value entity.Field
		if err := rows.Scan(
			&value.ID,
			&value.Name,
			&value.LocationX,
			&value.LocationY,
			&value.ObjectNum,
			&value.Level,
			&value.Difficulty,
		); err != nil {
			return values, xerrors.Errorf("cannot scan value: %w", err)
		}
		values = append(values, &value)
	}
	return values, nil
}

// generated by eevee
func (d *FieldImpl) FindByLocationX(ctx context.Context, a0 int) (r entity.Fields, e error) {
	values := entity.Fields{}
	query := "SELECT `id`, `name`, `location_x`, `location_y`, `object_num`, `level`, `difficulty` FROM `fields` WHERE `location_x` = ?"
	rows, err := d.tx.QueryContext(ctx, query, a0)
	if err != nil {
		return values, xerrors.Errorf("failure query %s: %w", query, err)
	}
	defer func() {
		if err := rows.Close(); err != nil {
			e = xerrors.Errorf("cannot close rows: %w", err)
		}
	}()
	for rows.Next() {
		var value entity.Field
		if err := rows.Scan(
			&value.ID,
			&value.Name,
			&value.LocationX,
			&value.LocationY,
			&value.ObjectNum,
			&value.Level,
			&value.Difficulty,
		); err != nil {
			return values, xerrors.Errorf("cannot scan value: %w", err)
		}
		values = append(values, &value)
	}
	return values, nil
}

// generated by eevee
func (d *FieldImpl) FindByLocationXAndLocationY(ctx context.Context, a0 int, a1 int) (r *entity.Field, e error) {
	var value entity.Field
	query := "SELECT `id`, `name`, `location_x`, `location_y`, `object_num`, `level`, `difficulty` FROM `fields` WHERE `location_x` = ? AND `location_y` = ?"
	if err := d.tx.QueryRowContext(ctx, query, a0, a1).Scan(
		&value.ID,
		&value.Name,
		&value.LocationX,
		&value.LocationY,
		&value.ObjectNum,
		&value.Level,
		&value.Difficulty,
	); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, xerrors.Errorf("failure query %s: %w", query, err)
	}
	return &value, nil
}

// generated by eevee
func (d *FieldImpl) FindByLocationXes(ctx context.Context, a0 []int) (r entity.Fields, e error) {
	values := entity.Fields{}
	query := "SELECT `id`, `name`, `location_x`, `location_y`, `object_num`, `level`, `difficulty` FROM `fields` WHERE `location_x` IN (%s)"
	args := []interface{}{}
	placeholders := make([]string, 0, len(a0))
	for _, v := range a0 {
		args = append(args, v)
		placeholders = append(placeholders, "?")
	}
	selectQuery := fmt.Sprintf(query, strings.Join(placeholders, ", "))
	rows, err := d.tx.QueryContext(ctx, selectQuery, args...)
	if err != nil {
		return values, xerrors.Errorf("failure query %s: %w", query, err)
	}
	defer func() {
		if err := rows.Close(); err != nil {
			e = xerrors.Errorf("cannot close rows: %w", err)
		}
	}()
	for rows.Next() {
		var value entity.Field
		if err := rows.Scan(
			&value.ID,
			&value.Name,
			&value.LocationX,
			&value.LocationY,
			&value.ObjectNum,
			&value.Level,
			&value.Difficulty,
		); err != nil {
			return values, xerrors.Errorf("cannot scan value: %w", err)
		}
		values = append(values, &value)
	}
	return values, nil
}

// generated by eevee
func (d *FieldImpl) FindByName(ctx context.Context, a0 string) (r *entity.Field, e error) {
	var value entity.Field
	query := "SELECT `id`, `name`, `location_x`, `location_y`, `object_num`, `level`, `difficulty` FROM `fields` WHERE `name` = ?"
	if err := d.tx.QueryRowContext(ctx, query, a0).Scan(
		&value.ID,
		&value.Name,
		&value.LocationX,
		&value.LocationY,
		&value.ObjectNum,
		&value.Level,
		&value.Difficulty,
	); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, xerrors.Errorf("failure query %s: %w", query, err)
	}
	return &value, nil
}

// generated by eevee
func (d *FieldImpl) FindByNames(ctx context.Context, a0 []string) (r entity.Fields, e error) {
	values := entity.Fields{}
	query := "SELECT `id`, `name`, `location_x`, `location_y`, `object_num`, `level`, `difficulty` FROM `fields` WHERE `name` IN (%s)"
	args := []interface{}{}
	placeholders := make([]string, 0, len(a0))
	for _, v := range a0 {
		args = append(args, v)
		placeholders = append(placeholders, "?")
	}
	selectQuery := fmt.Sprintf(query, strings.Join(placeholders, ", "))
	rows, err := d.tx.QueryContext(ctx, selectQuery, args...)
	if err != nil {
		return values, xerrors.Errorf("failure query %s: %w", query, err)
	}
	defer func() {
		if err := rows.Close(); err != nil {
			e = xerrors.Errorf("cannot close rows: %w", err)
		}
	}()
	for rows.Next() {
		var value entity.Field
		if err := rows.Scan(
			&value.ID,
			&value.Name,
			&value.LocationX,
			&value.LocationY,
			&value.ObjectNum,
			&value.Level,
			&value.Difficulty,
		); err != nil {
			return values, xerrors.Errorf("cannot scan value: %w", err)
		}
		values = append(values, &value)
	}
	return values, nil
}

// generated by eevee
func (d *FieldImpl) FindByObjectNum(ctx context.Context, a0 int) (r entity.Fields, e error) {
	values := entity.Fields{}
	query := "SELECT `id`, `name`, `location_x`, `location_y`, `object_num`, `level`, `difficulty` FROM `fields` WHERE `object_num` = ?"
	rows, err := d.tx.QueryContext(ctx, query, a0)
	if err != nil {
		return values, xerrors.Errorf("failure query %s: %w", query, err)
	}
	defer func() {
		if err := rows.Close(); err != nil {
			e = xerrors.Errorf("cannot close rows: %w", err)
		}
	}()
	for rows.Next() {
		var value entity.Field
		if err := rows.Scan(
			&value.ID,
			&value.Name,
			&value.LocationX,
			&value.LocationY,
			&value.ObjectNum,
			&value.Level,
			&value.Difficulty,
		); err != nil {
			return values, xerrors.Errorf("cannot scan value: %w", err)
		}
		values = append(values, &value)
	}
	return values, nil
}

// generated by eevee
func (d *FieldImpl) FindByObjectNums(ctx context.Context, a0 []int) (r entity.Fields, e error) {
	values := entity.Fields{}
	query := "SELECT `id`, `name`, `location_x`, `location_y`, `object_num`, `level`, `difficulty` FROM `fields` WHERE `object_num` IN (%s)"
	args := []interface{}{}
	placeholders := make([]string, 0, len(a0))
	for _, v := range a0 {
		args = append(args, v)
		placeholders = append(placeholders, "?")
	}
	selectQuery := fmt.Sprintf(query, strings.Join(placeholders, ", "))
	rows, err := d.tx.QueryContext(ctx, selectQuery, args...)
	if err != nil {
		return values, xerrors.Errorf("failure query %s: %w", query, err)
	}
	defer func() {
		if err := rows.Close(); err != nil {
			e = xerrors.Errorf("cannot close rows: %w", err)
		}
	}()
	for rows.Next() {
		var value entity.Field
		if err := rows.Scan(
			&value.ID,
			&value.Name,
			&value.LocationX,
			&value.LocationY,
			&value.ObjectNum,
			&value.Level,
			&value.Difficulty,
		); err != nil {
			return values, xerrors.Errorf("cannot scan value: %w", err)
		}
		values = append(values, &value)
	}
	return values, nil
}

// generated by eevee
func (d *FieldImpl) Update(ctx context.Context, value *entity.Field) (e error) {
	args := []interface{}{value.Name, value.LocationX, value.LocationY, value.ObjectNum, value.Level, value.Difficulty, value.ID}
	query := "UPDATE `fields` SET `name` = ?, `location_x` = ?, `location_y` = ?, `object_num` = ?, `level` = ?, `difficulty` = ? WHERE id = ?"
	if _, err := d.tx.ExecContext(ctx, query, args...); err != nil {
		return xerrors.Errorf("failure query %s: %w", query, err)
	}
	return nil
}

// generated by eevee
func (d *FieldImpl) UpdateByDifficultyAndLevel(ctx context.Context, a0 int, a1 int, updateMap map[string]interface{}) (e error) {
	columns := []string{}
	args := []interface{}{}
	for column, v := range updateMap {
		columns = append(columns, fmt.Sprintf("`%s` = ?", column))
		args = append(args, v)
	}
	args = append(args, a0)
	args = append(args, a1)
	query := fmt.Sprintf("UPDATE `fields` SET %s WHERE `difficulty` = ? AND `level` = ?", strings.Join(columns, ", "))
	if _, err := d.tx.ExecContext(ctx, query, args...); err != nil {
		return xerrors.Errorf("failure query %s: %w", query, err)
	}
	return nil
}

// generated by eevee
func (d *FieldImpl) UpdateByID(ctx context.Context, a0 uint64, updateMap map[string]interface{}) (e error) {
	columns := []string{}
	args := []interface{}{}
	for column, v := range updateMap {
		columns = append(columns, fmt.Sprintf("`%s` = ?", column))
		args = append(args, v)
	}
	args = append(args, a0)
	query := fmt.Sprintf("UPDATE `fields` SET %s WHERE `id` = ?", strings.Join(columns, ", "))
	if _, err := d.tx.ExecContext(ctx, query, args...); err != nil {
		return xerrors.Errorf("failure query %s: %w", query, err)
	}
	return nil
}

// generated by eevee
func (d *FieldImpl) UpdateByIDs(ctx context.Context, a0 []uint64, updateMap map[string]interface{}) (e error) {
	columns := []string{}
	args := []interface{}{}
	for column, v := range updateMap {
		columns = append(columns, fmt.Sprintf("`%s` = ?", column))
		args = append(args, v)
	}
	for _, v := range a0 {
		args = append(args, v)
	}
	placeholders := make([]string, 0, len(a0))
	for range a0 {
		placeholders = append(placeholders, "?")
	}
	query := fmt.Sprintf("UPDATE `fields` SET %s WHERE `id` IN (%s)", strings.Join(columns, ", "), strings.Join(placeholders, ", "))
	if _, err := d.tx.ExecContext(ctx, query, args...); err != nil {
		return xerrors.Errorf("failure query %s: %w", query, err)
	}
	return nil
}

// generated by eevee
func (d *FieldImpl) UpdateByLocationXAndLocationY(ctx context.Context, a0 int, a1 int, updateMap map[string]interface{}) (e error) {
	columns := []string{}
	args := []interface{}{}
	for column, v := range updateMap {
		columns = append(columns, fmt.Sprintf("`%s` = ?", column))
		args = append(args, v)
	}
	args = append(args, a0)
	args = append(args, a1)
	query := fmt.Sprintf("UPDATE `fields` SET %s WHERE `location_x` = ? AND `location_y` = ?", strings.Join(columns, ", "))
	if _, err := d.tx.ExecContext(ctx, query, args...); err != nil {
		return xerrors.Errorf("failure query %s: %w", query, err)
	}
	return nil
}

// generated by eevee
func (d *FieldImpl) UpdateByName(ctx context.Context, a0 string, updateMap map[string]interface{}) (e error) {
	columns := []string{}
	args := []interface{}{}
	for column, v := range updateMap {
		columns = append(columns, fmt.Sprintf("`%s` = ?", column))
		args = append(args, v)
	}
	args = append(args, a0)
	query := fmt.Sprintf("UPDATE `fields` SET %s WHERE `name` = ?", strings.Join(columns, ", "))
	if _, err := d.tx.ExecContext(ctx, query, args...); err != nil {
		return xerrors.Errorf("failure query %s: %w", query, err)
	}
	return nil
}

// generated by eevee
func (d *FieldImpl) UpdateByNames(ctx context.Context, a0 []string, updateMap map[string]interface{}) (e error) {
	columns := []string{}
	args := []interface{}{}
	for column, v := range updateMap {
		columns = append(columns, fmt.Sprintf("`%s` = ?", column))
		args = append(args, v)
	}
	for _, v := range a0 {
		args = append(args, v)
	}
	placeholders := make([]string, 0, len(a0))
	for range a0 {
		placeholders = append(placeholders, "?")
	}
	query := fmt.Sprintf("UPDATE `fields` SET %s WHERE `name` IN (%s)", strings.Join(columns, ", "), strings.Join(placeholders, ", "))
	if _, err := d.tx.ExecContext(ctx, query, args...); err != nil {
		return xerrors.Errorf("failure query %s: %w", query, err)
	}
	return nil
}

// generated by eevee
func (d *FieldImpl) UpdateByObjectNum(ctx context.Context, a0 int, updateMap map[string]interface{}) (e error) {
	columns := []string{}
	args := []interface{}{}
	for column, v := range updateMap {
		columns = append(columns, fmt.Sprintf("`%s` = ?", column))
		args = append(args, v)
	}
	args = append(args, a0)
	query := fmt.Sprintf("UPDATE `fields` SET %s WHERE `object_num` = ?", strings.Join(columns, ", "))
	if _, err := d.tx.ExecContext(ctx, query, args...); err != nil {
		return xerrors.Errorf("failure query %s: %w", query, err)
	}
	return nil
}

// generated by eevee
func (d *FieldImpl) UpdateByObjectNums(ctx context.Context, a0 []int, updateMap map[string]interface{}) (e error) {
	columns := []string{}
	args := []interface{}{}
	for column, v := range updateMap {
		columns = append(columns, fmt.Sprintf("`%s` = ?", column))
		args = append(args, v)
	}
	for _, v := range a0 {
		args = append(args, v)
	}
	placeholders := make([]string, 0, len(a0))
	for range a0 {
		placeholders = append(placeholders, "?")
	}
	query := fmt.Sprintf("UPDATE `fields` SET %s WHERE `object_num` IN (%s)", strings.Join(columns, ", "), strings.Join(placeholders, ", "))
	if _, err := d.tx.ExecContext(ctx, query, args...); err != nil {
		return xerrors.Errorf("failure query %s: %w", query, err)
	}
	return nil
}

func (d *FieldImpl) ExtendMethod() error {
	fmt.Println("ext")
	return nil
}
