// Code generated by eevee. DO NOT EDIT!

package model

import (
	"daoplugin/entity"
	"daoplugin/model"
)

func DefaultGroup() *model.Group {
	value := model.NewGroup(&entity.Group{
		ID:   1,
		Name: "",
	}, nil)
	return value
}

func DefaultsGroup() *model.Groups {
	values := model.NewGroups(entity.Groups{})
	values.Add(DefaultGroup())
	return values
}
