// Code generated by eevee. DO NOT EDIT!

package model

import (
	"context"
	"daoplugin/entity"
	"daoplugin/model"
)

func DefaultUser() *model.User {
	value := model.NewUser(&entity.User{
		Age:       0,
		FieldID:   0,
		GroupID:   0,
		ID:        1,
		Name:      "john",
		Sex:       "",
		SkillID:   0,
		SkillRank: 0,
		WorldID:   0,
	}, nil)
	value.UserFields = func(context.Context) (*model.UserFields, error) {
		return DefaultsUserField(), nil
	}
	value.Skill = func(context.Context) (*model.Skill, error) {
		return DefaultSkill(), nil
	}
	value.World = func(context.Context) (*model.World, error) {
		return DefaultWorld(), nil
	}
	return value
}

func DefaultsUser() *model.Users {
	values := model.NewUsers(entity.Users{})
	values.Add(DefaultUser())
	return values
}
