// Code generated by eevee. DO NOT EDIT!

package entity

type Skill struct {
	ID          uint64 `json:"id"`
	SkillEffect string `json:"skillEffect"`
}

type Skills []*Skill

func (e Skills) IDs() []uint64 {
	values := make([]uint64, 0, len(e))
	for _, value := range e {
		values = append(values, value.ID)
	}
	return values
}

func (e Skills) SkillEffects() []string {
	values := make([]string, 0, len(e))
	for _, value := range e {
		values = append(values, value.SkillEffect)
	}
	return values
}
