// Code generated by eevee. DO NOT EDIT!

package entity

type User struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`
}

type Users []*User

func (e Users) IDs() []uint64 {
	values := make([]uint64, 0, len(e))
	for _, value := range e {
		values = append(values, value.ID)
	}
	return values
}

func (e Users) Names() []string {
	values := make([]string, 0, len(e))
	for _, value := range e {
		values = append(values, value.Name)
	}
	return values
}
