// Code generated by eevee. DO NOT EDIT!

package repository

import (
	"/dao"
	"/entity"
	"/model"
	"context"
	"database/sql"

	"golang.org/x/xerrors"
)

type Skill interface {
	ToModel(*entity.Skill) *model.Skill
	ToModels(entity.Skills) *model.Skills
	Create(context.Context, *entity.Skill) (*model.Skill, error)
	Creates(context.Context, entity.Skills) (*model.Skills, error)
}

type SkillImpl struct {
	skillDAO dao.Skill
	repo     Repository
}

func NewSkill(ctx context.Context, tx *sql.Tx) *SkillImpl {
	return &SkillImpl{skillDAO: dao.NewSkill(ctx, tx)}
}

func (r *SkillImpl) ToModel(value *entity.Skill) *model.Skill {
	return r.createCollection(entity.Skills{value}).First()
}

func (r *SkillImpl) ToModels(values entity.Skills) *model.Skills {
	return r.createCollection(values)
}

func (r *SkillImpl) Create(ctx context.Context, value *entity.Skill) (*model.Skill, error) {
	if err := r.skillDAO.Create(ctx, value); err != nil {
		return nil, xerrors.Errorf("cannot Create: %w", err)
	}
	v := r.ToModel(value)
	v.SetSavedValue(value)
	v.SetAlreadyCreated(true)
	return v, nil
}

func (r *SkillImpl) Creates(ctx context.Context, entities entity.Skills) (*model.Skills, error) {
	for _, v := range entities {
		if _, err := r.Create(ctx, v); err != nil {
			return nil, xerrors.Errorf("cannot Create: %w", err)
		}
	}
	values := r.ToModels(entities)
	values.Each(func(v *model.Skill) {
		v.SetSavedValue(v.Skill)
		v.SetAlreadyCreated(true)
	})
	return values, nil
}

func (r *SkillImpl) createCollection(entities entity.Skills) *model.Skills {
	values := model.NewSkills(entities)
	for i := 0; i < len(entities); i += 1 {
		values.Add(r.create(entities[i], values))
	}
	return values
}

func (r *SkillImpl) create(entity *entity.Skill, values *model.Skills) *model.Skill {
	value := model.NewSkill(entity, r.skillDAO)
	value.SetConverter(r.repo.(model.ModelConverter))
	return value
}
