// Code generated by eevee. DO NOT EDIT!

package repository

import (
	"context"
	"database/sql"
	"relation/dao"
	"relation/entity"
	"relation/model"

	"golang.org/x/xerrors"
)

type Skill interface {
	ToModel(*entity.Skill) *model.Skill
	ToModels(entity.Skills) *model.Skills
	Create(context.Context, *entity.Skill) (*model.Skill, error)
	Creates(context.Context, entity.Skills) (*model.Skills, error)
	FindAll(context.Context) (*model.Skills, error)
	FindByID(context.Context, uint64) (*model.Skill, error)
	FindByIDs(context.Context, []uint64) (*model.Skills, error)
	UpdateByID(context.Context, uint64, map[string]interface{}) error
	UpdateByIDs(context.Context, []uint64, map[string]interface{}) error
	DeleteByID(context.Context, uint64) error
	DeleteByIDs(context.Context, []uint64) error
	Count(context.Context) (int64, error)
	Delete(context.Context, *entity.Skill) error
	Update(context.Context, *entity.Skill) error
}

type SkillImpl struct {
	skillDAO dao.Skill
	repo     Repository
}

func NewSkill(ctx context.Context, tx *sql.Tx) *SkillImpl {
	return &SkillImpl{skillDAO: dao.NewSkill(ctx, tx)}
}

func (r *SkillImpl) ToModel(value *entity.Skill) *model.Skill {
	return r.createCollection(entity.Skills{value}).First()
}

func (r *SkillImpl) ToModels(values entity.Skills) *model.Skills {
	return r.createCollection(values)
}

func (r *SkillImpl) Create(ctx context.Context, value *entity.Skill) (*model.Skill, error) {
	if err := r.skillDAO.Create(ctx, value); err != nil {
		return nil, xerrors.Errorf("cannot Create: %w", err)
	}
	v := r.ToModel(value)
	v.SetSavedValue(value)
	v.SetAlreadyCreated(true)
	return v, nil
}

func (r *SkillImpl) Creates(ctx context.Context, entities entity.Skills) (*model.Skills, error) {
	for _, v := range entities {
		if _, err := r.Create(ctx, v); err != nil {
			return nil, xerrors.Errorf("cannot Create: %w", err)
		}
	}
	values := r.ToModels(entities)
	values.Each(func(v *model.Skill) {
		v.SetSavedValue(v.Skill)
		v.SetAlreadyCreated(true)
	})
	return values, nil
}

func (r *SkillImpl) FindAll(a0 context.Context) (*model.Skills, error) {
	values, err := r.skillDAO.FindAll(a0)
	if err != nil {
		return nil, xerrors.Errorf("failed to FindAll: %w", err)
	}
	collection := r.createCollection(values)
	collection.Each(func(v *model.Skill) {
		v.SetSavedValue(v.Skill)
		v.SetAlreadyCreated(true)
	})
	return collection, nil
}

func (r *SkillImpl) FindByID(a0 context.Context, a1 uint64) (*model.Skill, error) {
	value, err := r.skillDAO.FindByID(a0, a1)
	if err != nil {
		return nil, xerrors.Errorf("failed to FindByID: %w", err)
	}
	if value == nil {
		return nil, nil
	}
	v := r.createCollection(entity.Skills{value}).First()
	v.SetSavedValue(v.Skill)
	v.SetAlreadyCreated(true)
	return v, nil
}

func (r *SkillImpl) FindByIDs(a0 context.Context, a1 []uint64) (*model.Skills, error) {
	values, err := r.skillDAO.FindByIDs(a0, a1)
	if err != nil {
		return nil, xerrors.Errorf("failed to FindByIDs: %w", err)
	}
	collection := r.createCollection(values)
	collection.Each(func(v *model.Skill) {
		v.SetSavedValue(v.Skill)
		v.SetAlreadyCreated(true)
	})
	return collection, nil
}

func (r *SkillImpl) UpdateByID(a0 context.Context, a1 uint64, a2 map[string]interface{}) error {
	if err := r.skillDAO.UpdateByID(a0, a1, a2); err != nil {
		return xerrors.Errorf("failed to update: %w", err)
	}
	return nil
}

func (r *SkillImpl) UpdateByIDs(a0 context.Context, a1 []uint64, a2 map[string]interface{}) error {
	if err := r.skillDAO.UpdateByIDs(a0, a1, a2); err != nil {
		return xerrors.Errorf("failed to update: %w", err)
	}
	return nil
}

func (r *SkillImpl) DeleteByID(a0 context.Context, a1 uint64) error {
	if err := r.skillDAO.DeleteByID(a0, a1); err != nil {
		return xerrors.Errorf("failed to delete: %w", err)
	}
	return nil
}

func (r *SkillImpl) DeleteByIDs(a0 context.Context, a1 []uint64) error {
	if err := r.skillDAO.DeleteByIDs(a0, a1); err != nil {
		return xerrors.Errorf("failed to delete: %w", err)
	}
	return nil
}

func (r *SkillImpl) Count(a0 context.Context) (r0 int64, r1 error) {
	r0, r1 = r.skillDAO.Count(a0)
	if r1 != nil {
		r1 = xerrors.Errorf("failed to Count: %w", r1)
	}
	return
}

func (r *SkillImpl) Delete(a0 context.Context, a1 *entity.Skill) (r0 error) {
	r0 = r.skillDAO.Delete(a0, a1)
	if r0 != nil {
		r0 = xerrors.Errorf("failed to Delete: %w", r0)
	}
	return
}

func (r *SkillImpl) Update(a0 context.Context, a1 *entity.Skill) (r0 error) {
	r0 = r.skillDAO.Update(a0, a1)
	if r0 != nil {
		r0 = xerrors.Errorf("failed to Update: %w", r0)
	}
	return
}

func (r *SkillImpl) createCollection(entities entity.Skills) *model.Skills {
	values := model.NewSkills(entities)
	for i := 0; i < len(entities); i += 1 {
		values.Add(r.create(entities[i], values))
	}
	return values
}

func (r *SkillImpl) create(entity *entity.Skill, values *model.Skills) *model.Skill {
	value := model.NewSkill(entity, r.skillDAO)
	value.SetConverter(r.repo.(model.ModelConverter))
	return value
}
